/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniProject;

import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class MainManuGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainManuGUI
     */
    ConvertTempperatureGUI frmConvertTemp = new ConvertTempperatureGUI();
    EmployeeBonus frmEmpBonus = new EmployeeBonus();
    public MainManuGUI() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code.+ The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpShow = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MunuConvertTempperatureGUI = new javax.swing.JMenu();
        MunuReport = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dpShow.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout dpShowLayout = new javax.swing.GroupLayout(dpShow);
        dpShow.setLayout(dpShowLayout);
        dpShowLayout.setHorizontalGroup(
            dpShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        dpShowLayout.setVerticalGroup(
            dpShowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 646, Short.MAX_VALUE)
        );

        MunuConvertTempperatureGUI.setBackground(new java.awt.Color(204, 204, 255));
        MunuConvertTempperatureGUI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniProject/thermometer.png"))); // NOI18N
        MunuConvertTempperatureGUI.setText("ConvertTempperatureGUI");
        MunuConvertTempperatureGUI.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MunuConvertTempperatureGUI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MunuConvertTempperatureGUI.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MunuConvertTempperatureGUI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MunuConvertTempperatureGUIMouseClicked(evt);
            }
        });
        jMenuBar1.add(MunuConvertTempperatureGUI);

        MunuReport.setBackground(new java.awt.Color(255, 204, 204));
        MunuReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/miniProject/bonus.png"))); // NOI18N
        MunuReport.setText("EmployeeBonus");
        MunuReport.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        MunuReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        MunuReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        MunuReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MunuReportMouseClicked(evt);
            }
        });
        jMenuBar1.add(MunuReport);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpShow)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MunuConvertTempperatureGUIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MunuConvertTempperatureGUIMouseClicked
        // TODO add your handling code here:
        this.dpShow.removeAll();
        this.dpShow.add(this.frmConvertTemp);
        this.frmConvertTemp.setVisible(true);
        this.frmConvertTemp.setSize(this.getSize());
        this.frmEmpBonus.setVisible(false);
        
    }//GEN-LAST:event_MunuConvertTempperatureGUIMouseClicked

    private void MunuReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MunuReportMouseClicked
        // TODO add your handling code here:
        this.dpShow.removeAll();
        this.dpShow.add(this.frmEmpBonus);
        this.frmEmpBonus.setVisible(true);
        this.frmEmpBonus.setSize(this.getSize());
        this.frmConvertTemp.setVisible(false);
    }//GEN-LAST:event_MunuReportMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainManuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainManuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainManuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainManuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainManuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MunuConvertTempperatureGUI;
    private javax.swing.JMenu MunuReport;
    private javax.swing.JDesktopPane dpShow;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
